# Generated by Django 4.1.3 on 2022-11-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_latitude_customuser_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
