# Generated by Django 4.1.3 on 2022-11-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_location_customuser_city_customuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
