# Generated by Django 4.1.3 on 2022-11-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='basics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prompts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
