# Generated by Django 4.1.3 on 2022-11-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customuser_basics_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='file_url',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='filename',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
