# Generated by Django 4.1.3 on 2022-11-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userimage_file_url_userimage_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='spot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
