# Generated by Django 4.1.3 on 2022-11-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_userimage_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
