# Generated by Django 4.1.3 on 2022-11-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prospect',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
