# Generated by Django 4.1.3 on 2022-11-23 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospect', '0003_remove_prospect_prospect_prospect_stranger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='stranger',
        ),
        migrations.AddField(
            model_name='prospect',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospect_prospects', to=settings.AUTH_USER_MODEL),
        ),
    ]
