# Generated by Django 4.1.3 on 2022-11-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stranger', '0001_initial'),
        ('prospect', '0004_remove_prospect_stranger_prospect_prospect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='prospect',
        ),
        migrations.AddField(
            model_name='prospect',
            name='stranger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospect_prospects', to='stranger.stranger'),
        ),
    ]
