# Generated by Django 4.1.3 on 2022-11-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stranger', '0001_initial'),
        ('prospect', '0005_remove_prospect_prospect_prospect_stranger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='stranger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospect', to='stranger.stranger'),
        ),
    ]
