# Generated by Django 4.1.3 on 2022-11-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0007_alter_prospect_stranger'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='matched',
            field=models.BooleanField(default=False),
        ),
    ]
