# Generated by Django 4.1.3 on 2022-12-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='age',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='distance_away',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='gender',
            field=models.CharField(blank=True, default='man', max_length=100, null=True),
        ),
    ]
