# Generated by Django 4.1.3 on 2022-12-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_setting_age_alter_setting_distance_away_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='age',
        ),
        migrations.AddField(
            model_name='setting',
            name='max_age',
            field=models.IntegerField(blank=True, default=36, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='min_age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
