# Generated by Django 4.1.3 on 2022-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_remove_setting_age_setting_max_age_setting_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='incognito',
            field=models.BooleanField(default=False),
        ),
    ]
